version: '3.9'
services:
  java_app:
    container_name: java_app
    image: proyecto-web:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/musiclist
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=secret
    depends_on:
        - java_db
  java_db:
    container_name: java_db
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret

